### ISSUE TITLE
Misspelled search terms yield poor suggestion

### ISSUE THREAD

**Issue by simplay** [rathrio/lists#16]
Below an example of the situation: I incorrectly was searching for _He Men_  (I should have searched for _He Man_).

<img width="1355" alt="issue_case" src="https://cloud.githubusercontent.com/assets/827143/23357625/efe84780-fcde-11e6-98ef-22dfa9563fd3.png">

**Suggestion**: Apply a distance measure between every retrieved suggestion and the initial (user provided) search word and then only list suggestions that exhibit a sufficient _small_ distance value. A handy measure for the word difference would be the so called [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance).

**Comment by rathrio** [comment]
I'll close this one for now, since the substrings approach is already pretty good!
