### ISSUE TITLE
Give credit to APIs used

### ISSUE THREAD

**Issue by rathrio** [rathrio/lists#29]
Mention which APIs are used to scrape data.

Where does that make the most sense?

**Comment by simplay** [comment]
How about pushing `credits.md` file that is similar to [this one](https://github.com/MovingBlocks/Terasology/blob/develop/docs/Credits.md)?

**Comment by rathrio** [comment]
I like this idea! It'd be neat to be able to render the same markdown file on the about page. I'll take care of this.
