### ISSUE TITLE
Item has many Labels -> Item belongs to one List?

### ISSUE THREAD

**Issue by rathrio** [rathrio/lists#47]
Does it make sense that items can have many labels, i.e., can occur in many lists?

The usecase I initially thought of was having some sort of inbox/starred list and that would have just been another label to assign.

I think it'd simplify things to just make items belong to just one category and solve any other nuances with tags or another attribute.

- [x] Make item belong to only one label
- [x] Rename Label to List

**Comment by rathrio** [comment]
@simplay what do you think?

**Comment by simplay** [comment]
**Short answer**: Items should have exactly one label. Also, your renaming suggestion makes sense to me.

There are two types of lists (i.e. labels): Predefined- and user defined lists.
 
Every predefined list uses a tailored scraper, which retrieves items that belong to the context of its particular list. Hence, such list items should only have assigned the list's label. 

Regarding the user specified lists, we should first think of when a user actually would create such a list. I can think of two usecases: Either, a predefined list is not specifical enough (say a user wants to define a dessert-, a soup-, an action movie- or early-access game list) or a list does not actually depend on any scraper. 

On one hand, when using **specific lists**, indeed, it could happen that a user would scrape for similar items as if he would have used the scraper from a predefined list. However, maintaining the content of the lists should be the user's responsibility.  And maybe it was on purpose that he added the same item to two different list. Think about a dessert list and a _my favorite recipes_ list, both could contain the same item but both items could exhibit different notes.

On the other hand **scraper less** lists exhibit items that we solely defined by the user. Think of a _TODO_ list: It would not make any sense to assign the movie label to such a todo list item.

Additionally, we could think of implementing a _copy_/_import_ function. Such a function would enable users to copy items to different lists. The item-copy-process would change the item's label (use the target list's label). Moreover, such a function could also be handy when we would want to implement a _recommend this item to another user_ feature.
